### PR TITLE
fix: add --set-as-default for nvidia-ctk

### PR DESCRIPTION
**Pull request by walkah**

### CODE REVIEW

**Comment by galaxyxtwo** [comment]
hi @walkah happy to merge this. Is this mostly for good practice or did you run into an issue where setting to default was required? Interested as we havent seen this issue come up.

**Comment by walkah** [comment]
> hi @walkah happy to merge this. Is this mostly for good practice or did you run into an issue where setting to default was required? Interested as we havent seen this issue come up.

@galaxyxtwo  Re: https://discord.com/channels/1212897693450641498/1222749187804758057/1275526303608606913 - it's a potential reason for GPU jobs failing (an RP tries to run a job, but docker isn't using the nvidia runtime for the container - so the GPU isn't available).

**Review by noryev — APPROVED** [review]
nice, thank you for fixing that! @walkah  This is correct per the nvidia docs too @galaxyxtwo 
Screenshot from 2024-08-22 11-51-03

**Comment by galaxyxtwo** [comment]
Appreciate it @walkah  !

**Pull request merged**
