### PR TITLE
Make IPFS_PATH env variable persistent at the user level

### PR DESCRIPTION
**Pull request by Rodebrechtd**

### CODE REVIEW

**Comment by PBillingsby** [comment]
We may want to account for people using Zsh files here also. Thoughts? @Rodebrechtd

**Comment by Rodebrechtd** [comment]
@PBillingsby, bash is the default shell for most Linux distributions, including Ubuntu. I suggest to keep it simple

**Review by PBillingsby — APPROVED** [review]
LGTM

**Review by galaxyxtwo — APPROVED** [review]
Looks good thanks.

**Pull request merged**
